# Generated by Django 5.0.1 on 2024-02-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
    ]
