# Generated by Django 5.0.1 on 2024-02-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0003_location_lat_location_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
